# Generated by Django 3.0.4 on 2020-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_danisman'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisman',
            name='slug',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
