# Generated by Django 3.0.4 on 2020-07-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_danisman_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanismanImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('danismans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.danisman')),
            ],
        ),
    ]
