# Generated by Django 3.0.4 on 2020-07-06 10:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_danismanimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DugunSalonu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
