# Generated by Django 3.0.4 on 2020-07-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_salonimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonimage',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
