# Generated by Django 3.0.4 on 2020-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200707_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='garaj',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mahalle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='product',
            name='semt',
        ),
        migrations.AddField(
            model_name='product',
            name='tip',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
