# Generated by Django 3.0.4 on 2020-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='danisman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
                ('soyisim', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
