# Generated by Django 3.0.4 on 2020-07-04 08:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_danisman'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisman',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
    ]
