# Generated by Django 3.0.4 on 2020-07-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_danisman_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisman',
            name='skype',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
