# Generated by Django 3.0.4 on 2020-07-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_danisman_skype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='danisman',
        ),
    ]
